Rscript toy2/code/extract_ipums.R
Rscript toy2/code/nh_dat_int.R
Rscript toy2/code/allocate_hh.R
Rscript toy2/code/sch_dat_int.R
Rscript toy2/code/hf_dat_int.R
Rscript toy2/code/wp_size_w_schnh.R
Rscript toy2/code/assign_worker.R
Rscript toy2/code/build_hh_network.R
Rscript toy2/code/assign_extracurricular.R
#Rscript toy2/code/export_gen_dat.R
